### ISSUE TITLE
FileNotFoundError:No such file or directory: './data/crossdock2020/selected_test_targets.types'

### ISSUE THREAD

**Issue by Hovi123123** [divelab/GraphBP#7]
Hi，thanks for your work!
When I run the `main_gen.py` , the following ERROR message is displayed:

> nohup: ignoring input
Epoch: 33
Traceback (most recent call last):
  File "main_gen.py", line 30, in <module>
    all_mol_dicts = runner.generate(num_gen, temperature=[node_temp, dist_temp, angle_temp, torsion_temp], max_atoms=max_atoms, min_atoms=min_atoms, focus_th=focus_th, contact_th=contact_th, add_final=True, known_binding_site=known_binding_site)
  File "/public/thw/GraphBP/GraphBP/runner.py", line 120, in generate
    data_lines = pd.read_csv(
  File "/home/anaconda/software/envs/GraphBP/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/anaconda/software/envs/GraphBP/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/anaconda/software/envs/GraphBP/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/anaconda/software/envs/GraphBP/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/anaconda/software/envs/GraphBP/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/anaconda/software/envs/GraphBP/lib/python3.8/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './data/crossdock2020/selected_test_targets.types'

Would you kindly help me to solve the problem ? Thanks !

**Comment by mengliu1998** [comment]
@Hovi123123, Did you download the dataset before running the code?

**Comment by Hovi123123** [comment]
Yes, I have downloaded the v1.1 dataset. Then I unpacked and partitioned the dataset as instructed.

**Comment by mengliu1998** [comment]
Can you manually check if the selected_test_targets.types file exists in the folder ./data/crossdock2020?

If not, you could manually download from https://github.com/mattragoza/LiGAN/tree/master/data/crossdock2020. Thank you.

**Comment by Hovi123123** [comment]
OK, thanks again ！
